# Generated by Django 5.2.5 on 2025-08-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='max_tokens',
            field=models.IntegerField(default=500, help_text='Maximum number of tokens in the AI response'),
        ),
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.CharField(default='gpt-4', help_text='The AI model to use for this agent', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='prompt',
            field=models.TextField(default='You are a helpful assistant.', help_text='The system prompt for the AI agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Controls randomness in the AI response (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='welcome_message',
            field=models.TextField(default='Hello! How can I help you today?', help_text='Initial message shown to users when they start a chat'),
        ),
        migrations.AddField(
            model_name='agent',
            name='widget_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for the chat widget (colors, position, etc.)'),
        ),
    ]
