[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'python39Packages.virtualenv', 'postgresql_14']

[phases.install]
cmds = [
    "cd /app/backend",
    "python -m venv /app/venv",
    "/app/venv/bin/pip install --upgrade pip",
    "/app/venv/bin/pip install -r /app/backend/requirements.txt"
]

[phases.build]
cmds = [
    # Skip collectstatic as we're using DISABLE_COLLECTSTATIC
    "echo 'Skipping collectstatic due to DISABLE_COLLECTSTATIC=1'"
]

[start]
cmd = "cd /app/backend && /app/venv/bin/gunicorn support_backend.wsgi"

[build.args]
PYTHON_VERSION = "3.9"

[build.environment]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app/backend"
DISABLE_COLLECTSTATIC = "1"
